/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicefx;

/**
 *
 * @author Eugene
 */
public class Book {
    private String title;
    private int year;
    private String author;
    private String publisher;
    private double price;
    
    public Book(){
        this.title = "";
        this.year = 1900;
        this.author = "";
        this.publisher = "";
        this.price = 10000;
    }
    
    public Book(String title, int year, String author, String publisher, double price){
        this.title = title;
        this.year = year;
        this.author = author;
        this.publisher = publisher;
        this.price = price;
    }

//    these setter getter are generated by Alt + Insert

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
    
}
